FrioBueno/FrioBueno/Models/Carga.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FrioBueno.Models
{
    public class Carga
    {
        [Display(Name = "N° Lote")]
        public int Id { get; set; } //Numero de Lote 
        public string Producto { get; set; }
        [Display(Name = "Tipo Producto")]
        public string TipoProducto { get; set; }
        public string UnidadSoportante { get; set; }
        public int CantidadUS { get; set; }
        public string Envase { get; set; }
        [Display(Name = "Kg Neto")]
        public string KgNeto { get; set; }

        [Display(Name = "Codigo Cliente")]
        public int IdCliente { get; set; }

        public Carga(int NumLote, string producto, string tipoProducto, string unidadSoporte, int cantidadUS, 
            string envase, string kgNeto)
        {
            this.Id = NumLote;
            this.Producto = producto;
            this.TipoProducto = tipoProducto;
            this.UnidadSoportante = unidadSoporte;
            this.CantidadUS = cantidadUS;
            this.Envase = envase;
            this.KgNeto = kgNeto;
        }

        public Carga()
        {

        }

        public static implicit operator TempDataAttribute(Carga v)
        {
            throw new NotImplementedException();
        }
    }
}

FrioBueno/FrioBueno/Controllers/CargasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;

namespace FrioBueno.Controllers
{
    public class CargasController : Controller
    {
        private readonly FrioBuenoContext _context;

        public CargasController(FrioBuenoContext context)
        {
            _context = context;
        }

        // GET: Cargas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Carga.ToListAsync());
        }
       
        // GET: Cargas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cargas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Producto,TipoProducto,UnidadSoportante,CantidadUS,Envase,KgNeto,IdCliente")] Carga carga)
        {
            
            if (ModelState.IsValid)
            {
                _context.Add(carga);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Clientes");
            }
            return View(carga);
        }

        // GET: Cargas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carga = await _context.Carga.SingleOrDefaultAsync(m => m.Id == id);
            if (carga == null)
            {
                return NotFound();
            }
            return View(carga);
        }

        // POST: Cargas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Producto,TipoProducto,UnidadSoportante,CantidadUS,Envase,KgNeto,IdCliente")] Carga carga)
        {
            if (id != carga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(carga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CargaExists(carga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(carga);
        }

        // GET: Cargas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var carga = await _context.Carga
                .SingleOrDefaultAsync(m => m.Id == id);
            if (carga == null)
            {
                return NotFound();
            }

            return View(carga);
        }

        // POST: Cargas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var carga = await _context.Carga.SingleOrDefaultAsync(m => m.Id == id);
            _context.Carga.Remove(carga);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Clientes");
        }

        private bool CargaExists(int id)
        {
            return _context.Carga.Any(e => e.Id == id);
        }
    }
}

FrioBueno/FrioBueno/Controllers/DetalleCargasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class DetalleCargasController : Controller
    {
        private readonly FrioBuenoContext _context;

        public DetalleCargasController(FrioBuenoContext context)
        {
            _context = context;
        }

        // GET: DetalleCargas
        public async Task<IActionResult> Index()
        {
            return View(await _context.DetalleCarga.ToListAsync());
        }

        // GET: DetalleCargas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DetalleCargas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCarga,Producto,Envase,CantidadEnvases,KgEnvase,FolioExterno")] DetalleCarga detalleCarga)
        {
            var carga = _context.Carga.Where(m => m.Id == detalleCarga.IdCarga).FirstOrDefault();
            int cantidadUS = Convert.ToInt32(carga.CantidadUS);
            
            var detallesCarga = _context.DetalleCarga.Where(dc => dc.IdCarga == carga.Id).ToList();

            int cantDetalle = detallesCarga.Capacity;
            if(cantidadUS > cantDetalle)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(detalleCarga);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Clientes");
                }
            }
            return RedirectToAction("Index", "Clientes");
        }

        // GET: DetalleCargas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleCarga = await _context.DetalleCarga.SingleOrDefaultAsync(m => m.Id == id);
            if (detalleCarga == null)
            {
                return NotFound();
            }
            return View(detalleCarga);
        }

        // POST: DetalleCargas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdCarga,Producto,Envase,CantidadEnvases,KgEnvase,FolioExterno")] DetalleCarga detalleCarga)
        {
            if (id != detalleCarga.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var producto = _context.Producto.SingleOrDefault(m => m.FolioInterno == detalleCarga.Id);
                    producto.FolioInterno = detalleCarga.Id;
                    producto.Nombre = detalleCarga.Producto;
                    producto.Envase = detalleCarga.Envase;
                    producto.CantidadEnvases = detalleCarga.CantidadEnvases;
                    producto.FolioExterno = detalleCarga.FolioExterno;

                    _context.Update(detalleCarga);
                    await _context.SaveChangesAsync();

                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetalleCargaExists(detalleCarga.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(detalleCarga);
        }

        // GET: DetalleCargas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detalleCarga = await _context.DetalleCarga
                .SingleOrDefaultAsync(m => m.Id == id);
            if (detalleCarga == null)
            {
                return NotFound();
            }

            return View(detalleCarga);
        }

        // POST: DetalleCargas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var detalleCarga = await _context.DetalleCarga.SingleOrDefaultAsync(m => m.Id == id);
            _context.DetalleCarga.Remove(detalleCarga);
            await _context.SaveChangesAsync();

            _context.Database.ExecuteSqlCommand("DELETE FROM Producto WHERE FolioInterno = @id",
                new SqlParameter("@id", id));
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool DetalleCargaExists(int id)
        {
            return _context.DetalleCarga.Any(e => e.Id == id);
        }
    }
}

FrioBueno/FrioBueno/Views/Cargas/Create.cshtml
@model FrioBueno.Models.Carga

@{
    ViewData["Title"] = "Crear";
    var idCliente = ViewContext.RouteData.Values["Id"];
    int id = Convert.ToInt32(idCliente);
}

<h2>Ingresar Datos de la Carga</h2>

<hr />
<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProducto" class="control-label"></label>
                <input asp-for="TipoProducto" class="form-control" />
                <span asp-validation-for="TipoProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnidadSoportante" class="control-label"></label>
                <input asp-for="UnidadSoportante" class="form-control" />
                <span asp-validation-for="UnidadSoportante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadUS" class="control-label"></label>
                <input asp-for="CantidadUS" class="form-control" />
                <span asp-validation-for="CantidadUS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Envase" class="control-label"></label>
                <input asp-for="Envase" class="form-control" />
                <span asp-validation-for="Envase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KgNeto" class="control-label"></label>
                <input asp-for="KgNeto" class="form-control" />
                <span asp-validation-for="KgNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" class="control-label"></label>
                <input asp-for="IdCliente" value="@id" class="form-control" readonly />
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Cargas" asp-action="Index" asp-route-id="@id">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrioBueno/FrioBueno/Views/Cargas/Delete.cshtml
@model FrioBueno.Models.Carga

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>

<h3>¿Esta seguro que desea eliminar la Carga?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Producto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Producto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoProducto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoProducto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UnidadSoportante)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UnidadSoportante)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CantidadUS)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CantidadUS)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Envase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Envase)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.KgNeto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.KgNeto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdCliente)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCliente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Volver a la Lista</a>
    </form>
</div>

FrioBueno/FrioBueno/Views/Cargas/Edit.cshtml
@model FrioBueno.Models.Carga

@{
    ViewData["Title"] = "Editar Carga";
}

<h2>Editar Carga</h2>

<hr />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Producto" class="control-label"></label>
                <input asp-for="Producto" class="form-control" />
                <span asp-validation-for="Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TipoProducto" class="control-label"></label>
                <input asp-for="TipoProducto" class="form-control" />
                <span asp-validation-for="TipoProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnidadSoportante" class="control-label"></label>
                <input asp-for="UnidadSoportante" class="form-control" />
                <span asp-validation-for="UnidadSoportante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadUS" class="control-label"></label>
                <input asp-for="CantidadUS" class="form-control" />
                <span asp-validation-for="CantidadUS" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Envase" class="control-label"></label>
                <input asp-for="Envase" class="form-control" />
                <span asp-validation-for="Envase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KgNeto" class="control-label"></label>
                <input asp-for="KgNeto" class="form-control" />
                <span asp-validation-for="KgNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCliente" type="hidden" class="control-label"></label>
                <input asp-for="IdCliente" type="hidden" class="form-control" readonly/>
                <span asp-validation-for="IdCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrioBueno/FrioBueno/Views/Cargas/Index.cshtml
@model IEnumerable<FrioBueno.Models.Carga>

@{
    ViewData["Title"] = "Carga";
    var idCliente = ViewContext.RouteData.Values["Id"];
    int id = Convert.ToInt32(idCliente);
}

<h2>Carga</h2>

<table class="table table-striped table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnidadSoportante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadUS)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Envase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KgNeto)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
    @foreach (var item in Model)
    {
        if (item.IdCliente == id)
        {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Producto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnidadSoportante)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadUS)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Envase)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KgNeto)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a> |
                        <a asp-action="Create" asp-controller="DetalleCargas" asp-route-id="@item.Id"> Agregar Detalle </a> |
                        <a asp-action="Index" asp-controller="DetalleCargas" asp-route-id="@item.Id"> Ver Detalle </a>
                    </td>
                </tr>
        }
    }
    </tbody>
</table>

@if(id == 0)
{
    <script>
        window.location.href = '@Url.Action("Index", "Clientes")';
    </script>
}