FrioBueno/FrioBueno/Controllers/UnidadesParaDespachosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class UnidadesParaDespachosController : Controller
    {
        private readonly FrioBuenoContext _context;

        public UnidadesParaDespachosController(FrioBuenoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto.ToListAsync());
        }

        public async Task<IActionResult> ShowProducts()
        {
            return View(await _context.ProductosParaDespacho.ToListAsync());
        }

        public async Task<IActionResult> AddUnits(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.SingleOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddUnits(int id, [Bind("Id,NumGuia,FolioExterno,FolioInterno,Nombre,Envase,CantidadEnvases")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            var prd = _context.ProductosParaDespacho.SingleOrDefault(m => m.IdProducto == id);

            if (prd == null)
            {
                var prod = _context.Producto.SingleOrDefault(m => m.Id == id);
                int CantidadEnvases = Convert.ToInt32(prod.CantidadEnvases);

                if (producto.CantidadEnvases > CantidadEnvases || producto.CantidadEnvases <= 0)
                {
                    return RedirectToAction(nameof(Index));
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Database.ExecuteSqlCommand("Insert into ProductosParaDespacho Values(@NumGuia, @FolioExterno, @FolioInterno, @Nombre, @Envase, @CantidadEnvases, @IdProducto)",
                            new SqlParameter("NumGuia", producto.NumGuia),
                            new SqlParameter("FolioExterno", producto.FolioExterno),
                            new SqlParameter("FolioInterno", producto.FolioInterno),
                            new SqlParameter("Nombre", producto.Nombre),
                            new SqlParameter("Envase", producto.Envase),
                            new SqlParameter("CantidadEnvases", producto.CantidadEnvases),
                            new SqlParameter("IdProducto", producto.Id)
                        );
                        await _context.SaveChangesAsync();

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductoExists(producto.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var producto = await _context.ProductosParaDespacho.SingleOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var producto = await _context.ProductosParaDespacho.SingleOrDefaultAsync(m => m.Id == id);

            _context.ProductosParaDespacho.Remove(producto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(ShowProducts));
        }

        public async Task<IActionResult> PackOff()
        {
            string TipoDespacho = "Despacho Unidades"; //Despacho por producto
            var productos = _context.ProductosParaDespacho.ToList();

            int numOrden;
            int NumGuia, FolioInterno, FolioExterno, CantidadEnvases;
            string Producto;

            var ultimo = _context.AsocDespachoProductos.LastOrDefault();
            //Solo para el primer Caso
            if (ultimo == null)
            {
                var UltimoDespacho = _context.Despacho.LastOrDefault();
                if (UltimoDespacho == null)
                {
                    numOrden = 1;
                }
                else
                {
                    numOrden = Convert.ToInt32(UltimoDespacho.NumOrden) + 1;
                }
                foreach (var producto in productos)
                {
                    NumGuia = Convert.ToInt32(producto.NumGuia);
                    FolioInterno = Convert.ToInt32(producto.FolioInterno);
                    FolioExterno = Convert.ToInt32(producto.FolioExterno);
                    Producto = Convert.ToString(producto.Nombre);
                    CantidadEnvases = Convert.ToInt32(producto.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                        new SqlParameter("NumOrden", numOrden),
                        new SqlParameter("TipoDespacho", TipoDespacho),
                        new SqlParameter("NumGuia", NumGuia),
                        new SqlParameter("FolioInterno", FolioInterno),
                        new SqlParameter("FolioExterno", FolioExterno),
                        new SqlParameter("Producto", Producto),
                        new SqlParameter("CantidadEnvases", CantidadEnvases)
                        );

                    await _context.SaveChangesAsync();
                }

            }
            else //Hay elementos en la tabla
            {
                numOrden = Convert.ToInt32(ultimo.NumOrden);
                _context.Database.ExecuteSqlCommand("DELETE FROM AsocDespachoProductos WHERE NumOrden = @numOrden",
                    new SqlParameter("@numOrden", numOrden)
                    );

                await _context.SaveChangesAsync();

                foreach (var producto in productos)
                {
                    NumGuia = Convert.ToInt32(producto.NumGuia);
                    FolioInterno = Convert.ToInt32(producto.FolioInterno);
                    FolioExterno = Convert.ToInt32(producto.FolioExterno);
                    Producto = Convert.ToString(producto.Nombre);
                    CantidadEnvases = Convert.ToInt32(producto.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                        new SqlParameter("NumOrden", numOrden),
                        new SqlParameter("TipoDespacho", TipoDespacho),
                        new SqlParameter("NumGuia", NumGuia),
                        new SqlParameter("FolioInterno", FolioInterno),
                        new SqlParameter("FolioExterno", FolioExterno),
                        new SqlParameter("Producto", Producto),
                        new SqlParameter("CantidadEnvases", CantidadEnvases)
                        );

                    await _context.SaveChangesAsync();
                }
            }
            return View(await _context.AsocDespachoProductos.Where(m => m.NumOrden == numOrden).ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Nombre, Patente, FechaDespacho, Temperatura, NumSello, IdOrden")] ClienteDespacho cliente)
        {
            var orden = _context.AsocDespachoProductos.LastOrDefault();
            cliente.IdOrden = orden.NumOrden;

            if (ModelState.IsValid)
            {
                _context.ClienteDespachos.Add(cliente);
                await _context.SaveChangesAsync();

                var despachos = from AsocDespachoProductos in _context.AsocDespachoProductos
                                join ClienteDespacho in _context.ClienteDespachos on AsocDespachoProductos.NumOrden equals ClienteDespacho.IdOrden
                                select new
                                {
                                    NumGuia = AsocDespachoProductos.NumGuia,
                                    FolioInterno = AsocDespachoProductos.FolioInterno,
                                    FolioExterno = AsocDespachoProductos.FolioExterno,
                                    NumOrden = AsocDespachoProductos.NumOrden,
                                    Cliente = ClienteDespacho.Nombre,
                                    TipoDespacho = AsocDespachoProductos.TipoDespacho,
                                    Producto = AsocDespachoProductos.Producto,
                                    CantidadEnvases = AsocDespachoProductos.CantidadEnvases
                                };


                foreach (var despacho in despachos.ToList())
                {
                    int NumGuia = Convert.ToInt32(despacho.NumGuia);
                    int FolioInterno = Convert.ToInt32(despacho.FolioInterno);

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/AddUnits.cshtml
@model FrioBueno.Models.Producto

@{
    ViewData["Title"] = "Agregar Producto";
}

<h2>Agregar Unidades al Despacho</h2>

<h4>¿ Desea agregar esta Tarja al despacho?</h4>
<hr />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form asp-action="AddUnits">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumGuia" class="control-label"></label>
                <input asp-for="NumGuia" class="form-control" readonly />
                <span asp-validation-for="NumGuia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolioExterno" class="control-label"></label>
                <input asp-for="FolioExterno" class="form-control" readonly />
                <span asp-validation-for="FolioExterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolioInterno" class="control-label"></label>
                <input asp-for="FolioInterno" class="form-control" readonly />
                <span asp-validation-for="FolioInterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" readonly />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Envase" class="control-label"></label>
                <input asp-for="Envase" class="form-control" readonly />
                <span asp-validation-for="Envase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadEnvases" class="control-label"></label>
                <input asp-for="CantidadEnvases" class="form-control" />
                <span asp-validation-for="CantidadEnvases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la Lista</a>
</div>

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/Cancel.cshtml
@model IEnumerable<AsocDespachoProductos>

@{
    ViewData["Title"] = "Cancelar";
}

<h2>¿Desea cancelar el despacho de los siguientes productos?</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumOrden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoDespacho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumGuia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioInterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioExterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadEnvases)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOrden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDespacho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="DeleteAll"> Cancelar Despacho </a> |
    <a asp-action="Index"> Volver a la Lista</a>
</div>

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/Create.cshtml
@model FrioBueno.Models.ClienteDespacho

@{
    ViewData["Title"] = "Datos Cliente";
}

<h2>Agregar Datos del Cliente</h2>

<div class="container">
    <div class="col-md-6 col-md-offset-3">
        <form asp-action="Create" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Patente" class="control-label"></label>
                <input asp-for="Patente" class="form-control" />
                <span asp-validation-for="Patente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDespacho" class="control-label"></label>
                <input asp-for="FechaDespacho" class="form-control" />
                <span asp-validation-for="FechaDespacho" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Temperatura" class="control-label"></label>
                <input asp-for="Temperatura" value="-18" class="form-control" />
                <span asp-validation-for="Temperatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumSello" class="control-label"></label>
                <input asp-for="NumSello" class="form-control" />
                <span asp-validation-for="NumSello" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Despachar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/Delete.cshtml
@model FrioBueno.Models.ProductosParaDespacho

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>
<h4>¿Esta seguro que desea eliminar las Unidades del Despacho?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumGuia)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumGuia)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FolioExterno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FolioExterno)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FolioInterno)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FolioInterno)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Envase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Envase)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CantidadEnvases)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CantidadEnvases)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-default" /> |
        <a asp-action="Index">Volver a la Lista</a>
    </form>
</div>

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/Index.cshtml
@model IEnumerable<FrioBueno.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h2>Productos Disponibles</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumGuia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioExterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioInterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Envase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadEnvases)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Envase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
                <td>
                    <a asp-action="AddUnits" asp-route-id="@item.Id">Agregar Unidades</a>

                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="ShowProducts" asp-controller="UnidadesParaDespachos"> Unidades para Despachar </a>

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/PackOff.cshtml
@model IEnumerable<FrioBueno.Models.AsocDespachoProductos>

    @{
    ViewData["Title"] = "Orden de Despacho";

    }

    <h2>Despacho de Tarjas</h2>

    <h4>
        Orden de Despacho con Tarjas Seleccionadas
    </h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NumOrden)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoDespacho)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NumGuia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FolioInterno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FolioExterno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Producto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadEnvases)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOrden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDespacho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
            </tr>
        }
        </tbody>
    </table>


    <a asp-action="Create" > Confirmar </a> |
    <a asp-action="Cancel"> Cancelar</a>

FrioBueno/FrioBueno/Views/UnidadesParaDespachos/ShowProducts.cshtml
@model IEnumerable<FrioBueno.Models.ProductosParaDespacho>

@{
    ViewData["Title"] = "Despacho Por Tarjas";
}

<h2>Productos Seleccionadas para Despacho</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumGuia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioExterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioInterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Envase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadEnvases)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Envase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id"> Eliminar </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="PackOff"> Despachar </a>
</div>