FrioBueno/FrioBueno/Models/ProductosParaDespacho.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace FrioBueno.Models
{
    public class ProductosParaDespacho
    {
        public int Id { get; set; }

        [Display(Name = "N° Guia")]
        public int NumGuia { get; set; }

        [Display(Name = "Folio Externo")]
        public int FolioExterno { get; set; }

        [Display(Name = "Folio Interno")]
        public int FolioInterno { get; set; }

        [Display(Name = "Producto")]
        public string Nombre { get; set; }

        public string Envase { get; set; }

        [Display(Name = "Cantidad Envases")]
        public int CantidadEnvases { get; set; }

        public int IdProducto { get; set; }

        public ProductosParaDespacho(int id, int numGuia, int folioExterno, int folioInterno, string nombre, string envase, int cantidadEnvases,
            int idProducto)
        {
            Id = id;
            NumGuia = numGuia;
            FolioExterno = FolioExterno;
            FolioInterno = FolioInterno;
            Nombre = nombre;
            Envase = envase;
            CantidadEnvases = cantidadEnvases;
            IdProducto = idProducto;
        }

        public ProductosParaDespacho()
        {

        }
    }
}

FrioBueno/FrioBueno/Controllers/DespachoTarjasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class DespachoTarjasController : Controller
    {

        private readonly FrioBuenoContext _context;

        public DespachoTarjasController(FrioBuenoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.ProductosParaDespacho.ToListAsync());
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var producto = await _context.ProductosParaDespacho.SingleOrDefaultAsync(m => m.Id == id);
            if( producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var producto = await _context.ProductosParaDespacho.SingleOrDefaultAsync(m => m.Id == id);

            _context.ProductosParaDespacho.Remove(producto);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "ProductosParaDespachos");
        }

        public async Task<IActionResult> PackOff()
        {
            string TipoDespacho = "Despacho Tarjas"; //Despacho por producto
            var productos = _context.ProductosParaDespacho.ToList();

            int numOrden;
            int NumGuia, FolioInterno, FolioExterno, CantidadEnvases;
            string Producto;

            var ultimo = _context.AsocDespachoProductos.LastOrDefault();
            //Solo para el primer Caso
            if (ultimo == null)
            {
                var UltimoDespacho = _context.Despacho.LastOrDefault();
                if(UltimoDespacho == null)
                {
                    numOrden = 1;
                }
                else
                {
                    numOrden = Convert.ToInt32(UltimoDespacho.NumOrden) + 1; 
                }
                foreach( var producto in productos)
                {
                    NumGuia = Convert.ToInt32(producto.NumGuia);
                    FolioInterno = Convert.ToInt32(producto.FolioInterno);
                    FolioExterno = Convert.ToInt32(producto.FolioExterno);
                    Producto = Convert.ToString(producto.Nombre);
                    CantidadEnvases = Convert.ToInt32(producto.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                        new SqlParameter("NumOrden", numOrden),
                        new SqlParameter("TipoDespacho", TipoDespacho),
                        new SqlParameter("NumGuia", NumGuia),
                        new SqlParameter("FolioInterno", FolioInterno),
                        new SqlParameter("FolioExterno", FolioExterno),
                        new SqlParameter("Producto", Producto),
                        new SqlParameter("CantidadEnvases", CantidadEnvases)
                        );

                    await _context.SaveChangesAsync();
                }
                
            }
            else //Hay elementos en la tabla
            {
                numOrden = Convert.ToInt32(ultimo.NumOrden);
                _context.Database.ExecuteSqlCommand("DELETE FROM AsocDespachoProductos WHERE NumOrden = @numOrden",
                    new SqlParameter("@numOrden", numOrden)
                    );

                await _context.SaveChangesAsync();

                foreach (var producto in productos)
                {
                    NumGuia = Convert.ToInt32(producto.NumGuia);
                    FolioInterno = Convert.ToInt32(producto.FolioInterno);
                    FolioExterno = Convert.ToInt32(producto.FolioExterno);
                    Producto = Convert.ToString(producto.Nombre);
                    CantidadEnvases = Convert.ToInt32(producto.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                        new SqlParameter("NumOrden", numOrden),
                        new SqlParameter("TipoDespacho", TipoDespacho),
                        new SqlParameter("NumGuia", NumGuia),
                        new SqlParameter("FolioInterno", FolioInterno),
                        new SqlParameter("FolioExterno", FolioExterno),
                        new SqlParameter("Producto", Producto),
                        new SqlParameter("CantidadEnvases", CantidadEnvases)
                        );

                    await _context.SaveChangesAsync();
                }
            }
            return View(await _context.AsocDespachoProductos.Where(m => m.NumOrden == numOrden).ToListAsync());
        }

        public async Task<IActionResult> Cancel()
        {
            return View(await _context.AsocDespachoProductos.ToListAsync());
        }

        public async Task<IActionResult> DeleteAll()
        {
            var productosDespachos = _context.AsocDespachoProductos.ToList();
            _context.AsocDespachoProductos.RemoveRange(productosDespachos);

            await _context.SaveChangesAsync();

            var productos = _context.ProductosParaDespacho.ToList();
            _context.ProductosParaDespacho.RemoveRange(productos);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "ProductosParaDespachos");
        }

        public bool ProductExists(int id)
        {
            return _context.ProductosParaDespacho.Any(m => m.Id == id);
        }
    }
}

FrioBueno/FrioBueno/Controllers/ProductosParaDespachosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class ProductosParaDespachosController : Controller
    {
        private readonly FrioBuenoContext _context;

        public ProductosParaDespachosController(FrioBuenoContext context)
        {
            _context = context;
        }

        // GET: ProductosParaDespachos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto.ToListAsync());
        }

        // GET: ProductosParaDespachos/AddProducto/5
        public async Task<IActionResult> AddProducto(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.SingleOrDefaultAsync(m => m.Id == id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: ProductosParaDespachos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddProducto(int id, [Bind("Id,NumGuia,FolioExterno,FolioInterno,Nombre,Envase,CantidadEnvases")] Producto producto)
        {
            if (id != producto.Id)
            {
                return NotFound();
            }

            var prd = _context.ProductosParaDespacho.SingleOrDefault(m => m.IdProducto == id);

            if (prd == null)
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Database.ExecuteSqlCommand("Insert into ProductosParaDespacho Values(@NumGuia, @FolioExterno, @FolioInterno, @Nombre, @Envase, @CantidadEnvases, @IdProducto)",
                            new SqlParameter("NumGuia", producto.NumGuia),
                            new SqlParameter("FolioExterno", producto.FolioExterno),
                            new SqlParameter("FolioInterno", producto.FolioInterno),
                            new SqlParameter("Nombre", producto.Nombre),
                            new SqlParameter("Envase", producto.Envase),
                            new SqlParameter("CantidadEnvases", producto.CantidadEnvases),
                            new SqlParameter("IdProducto", producto.Id)
                        );
                        await _context.SaveChangesAsync();

                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductoExists(producto.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Producto.Any(e => e.Id == id);
        }
    }
}

FrioBueno/FrioBueno/Views/ProductosParaDespachos/AddProducto.cshtml
@model FrioBueno.Models.Producto

@{
    ViewData["Title"] = "Agregar Producto";
}

<h2>Agregar Tarja al Despacho</h2>

<h4>¿ Desea agregar esta Tarja al despacho?</h4>
<hr />
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form asp-action="AddProducto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NumGuia" class="control-label"></label>
                <input asp-for="NumGuia" class="form-control" readonly />
                <span asp-validation-for="NumGuia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolioExterno" class="control-label"></label>
                <input asp-for="FolioExterno" class="form-control" readonly />
                <span asp-validation-for="FolioExterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FolioInterno" class="control-label"></label>
                <input asp-for="FolioInterno" class="form-control" readonly/>
                <span asp-validation-for="FolioInterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" readonly />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Envase" class="control-label"></label>
                <input asp-for="Envase" class="form-control" readonly/>
                <span asp-validation-for="Envase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadEnvases" class="control-label"></label>
                <input asp-for="CantidadEnvases" class="form-control" readonly/>
                <span asp-validation-for="CantidadEnvases" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a la Lista</a>
</div>

FrioBueno/FrioBueno/Views/ProductosParaDespachos/Index.cshtml
@model IEnumerable<FrioBueno.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h2>Tarjas Disponibles</h2>


<table class="table table-striped">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.NumGuia)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FolioExterno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FolioInterno)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Envase)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadEnvases)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NumGuia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FolioExterno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FolioInterno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Envase)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantidadEnvases)
            </td>
            <td>
                <a asp-action="AddProducto" asp-route-id="@item.Id">Agregar Producto</a> 

            </td>
        </tr>
}
    </tbody>
</table>

<a asp-action="Index" asp-controller="DespachoTarjas"> Tarjas para Despachar </a>