FrioBueno/FrioBueno/Controllers/ClienteDespachosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class ClienteDespachosController : Controller
    {
        private readonly FrioBuenoContext _context;

        public ClienteDespachosController(FrioBuenoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Despacho.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id, Nombre, Patente, FechaDespacho, Temperatura, NumSello, IdOrden")] ClienteDespacho cliente)
        {
            var orden = _context.AsocDespachoProductos.LastOrDefault();
            bool isDespachoLotes = false;

            if (orden.TipoDespacho.ToString().Equals("Despacho Lotes"))
            {
                isDespachoLotes = true;
            }

            cliente.IdOrden = orden.NumOrden;

            if(ModelState.IsValid)
            {
                _context.ClienteDespachos.Add(cliente);
                await _context.SaveChangesAsync();

                var despachos = from AsocDespachoProductos in _context.AsocDespachoProductos
                                join ClienteDespacho in _context.ClienteDespachos on AsocDespachoProductos.NumOrden equals ClienteDespacho.IdOrden
                                select new
                                {
                                    NumGuia = AsocDespachoProductos.NumGuia,
                                    FolioInterno = AsocDespachoProductos.FolioInterno,
                                    FolioExterno = AsocDespachoProductos.FolioExterno,
                                    NumOrden = AsocDespachoProductos.NumOrden,
                                    Cliente = ClienteDespacho.Nombre,
                                    TipoDespacho = AsocDespachoProductos.TipoDespacho,
                                    Producto = AsocDespachoProductos.Producto,
                                    CantidadEnvases = AsocDespachoProductos.CantidadEnvases
                                };


                foreach(var despacho in despachos.ToList())
                {
                    int NumGuia = Convert.ToInt32(despacho.NumGuia);
                    int FolioInterno = Convert.ToInt32(despacho.FolioInterno);
                    int FolioExterno = Convert.ToInt32(despacho.FolioExterno);
                    int NumOrden = Convert.ToInt32(despacho.NumOrden);
                    string Cliente = Convert.ToString(despacho.Cliente);
                    string TipoDespacho = Convert.ToString(despacho.TipoDespacho);
                    string Producto = Convert.ToString(despacho.Producto);
                    int CantidadEnvases = Convert.ToInt32(despacho.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO Despacho VALUES (@NumGuia, @FolioInterno, @FolioExterno, @NumOrden, @Cliente," +
                        "@TipoDespacho, @Producto, @CantidadEnvases)",
                        new SqlParameter("NumGuia", NumGuia),
                        new SqlParameter("FolioInterno", FolioInterno),
                        new SqlParameter("FolioExterno", FolioExterno),
                        new SqlParameter("NumOrden", NumOrden),
                        new SqlParameter("Cliente", Cliente),
                        new SqlParameter("TipoDespacho", TipoDespacho),
                        new SqlParameter("Producto", Producto),
                        new SqlParameter("CantidadEnvases", CantidadEnvases)
                        );

                    var detalle = _context.DetalleCarga.FirstOrDefault(m => m.Id == FolioInterno);
                    int idCarga = Convert.ToInt32(detalle.IdCarga);

                    await _context.SaveChangesAsync();

                    _context.Database.ExecuteSqlCommand("Delete from ProductosParaDespacho Where FolioInterno = @FolioInterno",
                        new SqlParameter("FolioInterno", FolioInterno)
                        );

                    _context.Database.ExecuteSqlCommand("Delete from Producto Where FolioInterno = @FolioInterno",
                            new SqlParameter("FolioInterno", FolioInterno)
                            );

                    _context.Database.ExecuteSqlCommand("Delete from DetalleCarga Where Id = @FolioInterno",
                            new SqlParameter("FolioInterno", FolioInterno)
                            );


                    var detalles = _context.DetalleCarga.Where(m => m.IdCarga == idCarga).ToList();
                    var carga = _context.Carga.FirstOrDefault(m => m.Id == idCarga);
                    if (detalles.Count() == 0)
                    {
                        _context.Carga.Remove(carga);
                        await _context.SaveChangesAsync();
                    }

                    await _context.SaveChangesAsync();
                }
                
                if(isDespachoLotes)
                {
                    var lotes = _context.LotesParaDespacho.ToList();
                    foreach( var lote in lotes)
                    {
                        int idCarga = Convert.ToInt32(lote.IdCarga);

                        _context.LotesParaDespacho.Remove(lote);
                        await _context.SaveChangesAsync();

                        var carga = _context.Carga.SingleOrDefault(m => m.Id == idCarga);
                        _context.Carga.Remove(carga);

                        await _context.SaveChangesAsync();
                    }
                }

                var productos = _context.AsocDespachoProductos.ToList();
                _context.AsocDespachoProductos.RemoveRange(productos);
                await _context.SaveChangesAsync();

                var clientes = _context.ClienteDespachos.ToList();
                _context.ClienteDespachos.RemoveRange(clientes);
                await _context.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

FrioBueno/FrioBueno/Controllers/DespachoLotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrioBueno.Models;
using System.Data.SqlClient;

namespace FrioBueno.Controllers
{
    public class DespachoLotesController : Controller
    {

        private readonly FrioBuenoContext _context;

        public DespachoLotesController(FrioBuenoContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.LotesParaDespacho.ToListAsync());
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var lote = await _context.LotesParaDespacho.SingleOrDefaultAsync(m => m.Id == id);
            if(lote == null)
            {
                return NotFound();
            }
            return View(lote);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var lote = await _context.LotesParaDespacho.SingleOrDefaultAsync(m => m.Id == id);

            _context.LotesParaDespacho.Remove(lote);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "LotesParaDespachos");
        }

        public async Task<IActionResult> PackOff()
        {
            string TipoDespacho = "Despacho Lotes";


            int numOrden;
            int NumGuia, FolioInterno, FolioExterno;
            string NombreProducto;
            int CantidadEnvases;

            var ultimo = _context.AsocDespachoProductos.LastOrDefault();
            if(ultimo == null)
            {
                var UltimoDespacho = _context.Despacho.LastOrDefault();
                if (UltimoDespacho == null)
                {
                    numOrden = 1;
                }
                else
                {
                    numOrden = Convert.ToInt32(UltimoDespacho.NumOrden) + 1;
                }
                var productos = from LotesParaDespacho in _context.LotesParaDespacho
                              join DetalleCarga in _context.DetalleCarga on LotesParaDespacho.IdCarga equals DetalleCarga.IdCarga
                              join Producto in _context.Producto on DetalleCarga.Id equals Producto.FolioInterno
                              select new
                              {
                                  NumGuia = Producto.NumGuia,
                                  FolioInterno = DetalleCarga.Id,
                                  FolioExterno = DetalleCarga.FolioExterno,
                                  Nombre = DetalleCarga.Producto,
                                  CantidadEnvases = Producto.CantidadEnvases
                                };
                
                foreach(var prod in productos)
                {
                    NumGuia = Convert.ToInt32(prod.NumGuia);
                    FolioInterno = Convert.ToInt32(prod.FolioInterno);
                    FolioExterno = Convert.ToInt32(prod.FolioExterno);
                    NombreProducto = Convert.ToString(prod.Nombre);
                    CantidadEnvases = Convert.ToInt32(prod.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                            new SqlParameter("NumOrden", numOrden),
                            new SqlParameter("TipoDespacho", TipoDespacho),
                            new SqlParameter("NumGuia", NumGuia),
                            new SqlParameter("FolioInterno", FolioInterno),
                            new SqlParameter("FolioExterno", FolioExterno),
                            new SqlParameter("Producto", NombreProducto),
                            new SqlParameter("CantidadEnvases", CantidadEnvases)
                    );

                    await _context.SaveChangesAsync();
                }
            }
            else
            {
                numOrden = Convert.ToInt32(ultimo.NumOrden);
                _context.Database.ExecuteSqlCommand("DELETE FROM AsocDespachoProductos WHERE NumOrden = @numOrden",
                    new SqlParameter("@numOrden", numOrden)
                    );

                await _context.SaveChangesAsync();

                var productos = from LotesParaDespacho in _context.LotesParaDespacho
                                join DetalleCarga in _context.DetalleCarga on LotesParaDespacho.IdCarga equals DetalleCarga.IdCarga
                                join Producto in _context.Producto on DetalleCarga.Id equals Producto.FolioInterno
                                select new
                                {
                                    NumGuia = Producto.NumGuia,
                                    FolioInterno = DetalleCarga.Id,
                                    FolioExterno = DetalleCarga.FolioExterno,
                                    Nombre = DetalleCarga.Producto,
                                    CantidadEnvases = Producto.CantidadEnvases
                                };

                foreach (var prod in productos)
                {
                    NumGuia = Convert.ToInt32(prod.NumGuia);
                    FolioInterno = Convert.ToInt32(prod.FolioInterno);
                    FolioExterno = Convert.ToInt32(prod.FolioExterno);
                    NombreProducto = Convert.ToString(prod.Nombre);
                    CantidadEnvases = Convert.ToInt32(prod.CantidadEnvases);

                    _context.Database.ExecuteSqlCommand("INSERT INTO AsocDespachoProductos VALUES(@NumOrden, @TipoDespacho, @NumGuia, @FolioInterno, @FolioExterno, @Producto, @CantidadEnvases)",
                            new SqlParameter("NumOrden", numOrden),
                            new SqlParameter("TipoDespacho", TipoDespacho),
                            new SqlParameter("NumGuia", NumGuia),
                            new SqlParameter("FolioInterno", FolioInterno),
                            new SqlParameter("FolioExterno", FolioExterno),
                            new SqlParameter("Producto", NombreProducto),
                            new SqlParameter("CantidadEnvases", CantidadEnvases)
                    );

                    await _context.SaveChangesAsync();
                }

            }

            return View(await _context.AsocDespachoProductos.Where(m => m.NumOrden == numOrden).ToListAsync());
        }

        public async Task<IActionResult> Cancel()
        {
            return View(await _context.AsocDespachoProductos.ToListAsync());
        }

        public async Task<IActionResult> DeleteAll()
        {
            var productosDespachos = _context.AsocDespachoProductos.ToList();
            _context.AsocDespachoProductos.RemoveRange(productosDespachos);

            await _context.SaveChangesAsync();

            var lotes = _context.LotesParaDespacho.ToList();
            _context.LotesParaDespacho.RemoveRange(lotes);

            await _context.SaveChangesAsync();

            return RedirectToAction("Index", "LotesParaDespachos");
        }
    }
}

FrioBueno/FrioBueno/Views/DespachoLotes/Cancel.cshtml
@model IEnumerable<AsocDespachoProductos>

@{
    ViewData["Title"] = "Cancelar";
}

<h2>¿Desea cancelar el despacho de los siguientes productos?</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumOrden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoDespacho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumGuia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioInterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioExterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadEnvases)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOrden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDespacho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="DeleteAll"> Cancelar Despacho </a> |
    <a asp-action="Index"> Volver a la Lista</a>
</div>

FrioBueno/FrioBueno/Views/DespachoLotes/Delete.cshtml
@model FrioBueno.Models.LotesParaDespacho

@{
    ViewData["Title"] = "Eliminar";
}

<h2>Eliminar</h2>
<h4>¿Esta seguro que desea eliminar el Lote del Despacho?</h4>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCarga)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdCarga)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TipoProducto)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TipoProducto)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Envase)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Envase)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-default" />
        <a asp-action="Index">Volver a la Lista</a>
    </form>
</div>

FrioBueno/FrioBueno/Views/DespachoLotes/Index.cshtml
@model IEnumerable<FrioBueno.Models.LotesParaDespacho>

@{
    ViewData["Title"] = "Despacho por Lotes";
}

<h2>Lotes Seleccionados Para Despacho</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdCarga)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Envase)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCarga)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoProducto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Envase)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id"> Eliminar </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="PackOff"> Despachar </a> 

FrioBueno/FrioBueno/Views/DespachoLotes/PackOff.cshtml
@model IEnumerable<FrioBueno.Models.AsocDespachoProductos>

@{
    ViewData["Title"] = "Orden de Despacho";
}

<h2>Despacho de Tarjas</h2>

<h4>
    Orden de Despacho con Tarjas de Lotes Seleccionados
</h4>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NumOrden)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoDespacho)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumGuia)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioInterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FolioExterno)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantidadEnvases)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NumOrden)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoDespacho)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumGuia)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioInterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FolioExterno)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CantidadEnvases)
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-action="Create" asp-controller="ClienteDespachos"> Confirmar </a> |
<a asp-action="Cancel" asp-controller="DespachoLotes"> Cancelar</a>